import "./admin-user";
import "./profile-edit-profile";
import "./profile-edit-password";
import './patient';
import './secretary';
import './dentist';
import './service';
import './schedule';
import './appointment';
